spring.application.name=demo
server.port=9091
management.endpoints.web.exposure.include=health, cache
management.endpoints.web.exposure.exclude=*
management.endpoint.health.show-details=always
info.app.name=Demo Spring Application
info.app.version=1.0.0
management.info.env.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:32768/testdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true